[manifest]
version = "1.0.0"
dump_lua = true
priority = 0



# Make Playing cards square
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''
if center.name == "Square Joker" and (center.discovered or self.bypass_discovery_center) then 
'''
position = 'at'
payload = '''
if center.name == "Square Joker" and (center.discovered or self.bypass_discovery_center) or 
    center.set == 'Default' or center.set == 'Enhanced' then 
'''
match_indent = true